### ISSUE TITLE
AddDbContext() call

### ISSUE THREAD

**Issue by Arnab-Developer** [anuraj/MinimalApi#1]
In your example I can't find any call to `AddDbContext()`. I checked [this](https://github.com/davidfowl/CommunityStandUpMinimalAPI/blob/main/TodoApi/Program.cs) repo and found that it has a `AddDbContext()` call in it. Is there anything I am missing?

**Comment by anuraj** [comment]
Looks like I missed it while committing the code. Maybe refactoring could be caused this issue.

**Comment by Arnab-Developer** [comment]
Thanks
